# Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

print(f'{"DESAFIO 009":=^20}')

n = int(input("Informe um numero: "))

print("A Tabuada do {} é.".format(n))

print(f"||{'MULTIPLICAÇÃO':=^15}||")
print(f'||{f"{n} x 0 = {n * 0}":^15}||')
print(f'||{f"{n} x 1 = {n * 1}":^15}||')
print(f'||{f"{n} x 2 = {n * 2}":^15}||')
print(f'||{f"{n} x 3 = {n * 3}":^15}||')
print(f'||{f"{n} x 4 = {n * 4}":^15}||')
print(f'||{f"{n} x 5 = {n * 5}":^15}||')
print(f'||{f"{n} x 6 = {n * 6}":^15}||')
print(f'||{f"{n} x 7 = {n * 7}":^15}||')
print(f'||{f"{n} x 8 = {n * 8}":^15}||')
print(f'||{f"{n} x 9 = {n * 9}":^15}||')

print(f"||{'DIVISÃO':=^15}||")
#print(f'||{f"{n} / 0 = {(n / 0):.3f}":^15}||') A divisão por zero resulta em erro
print(f'||{f"{n} / 1 = {(n / 1):.3f}":^15}||')
print(f'||{f"{n} / 2 = {(n / 2):.3f}":^15}||')
print(f'||{f"{n} / 3 = {(n / 3):.3f}":^15}||')
print(f'||{f"{n} / 4 = {(n / 4):.3f}":^15}||')
print(f'||{f"{n} / 5 = {(n / 5):.3f}":^15}||')
print(f'||{f"{n} / 6 = {(n / 6):.3f}":^15}||')
print(f'||{f"{n} / 7 = {(n / 7):.3f}":^15}||')
print(f'||{f"{n} / 8 = {(n / 8):.3f}":^15}||')
print(f'||{f"{n} / 9 = {(n / 9):.3f}":^15}||')

print(f"||{'ADIÇÃO':=^15}||")
print(f'||{f"{n} + 0 = {n + 0}":^15}||')
print(f'||{f"{n} + 1 = {n + 1}":^15}||')
print(f'||{f"{n} + 2 = {n + 2}":^15}||')
print(f'||{f"{n} + 3 = {n + 3}":^15}||')
print(f'||{f"{n} + 4 = {n + 4}":^15}||')
print(f'||{f"{n} + 5 = {n + 5}":^15}||')
print(f'||{f"{n} + 6 = {n + 6}":^15}||')
print(f'||{f"{n} + 7 = {n + 7}":^15}||')
print(f'||{f"{n} + 8 = {n + 8}":^15}||')
print(f'||{f"{n} + 9 = {n + 9}":^15}||')

print(f"||{'SUBTRAÇÃO':=^15}||")
print(f'||{f"{n} - 0 = {n - 0}":^15}||')
print(f'||{f"{n} - 1 = {n - 1}":^15}||')
print(f'||{f"{n} - 2 = {n - 2}":^15}||')
print(f'||{f"{n} - 3 = {n - 3}":^15}||')
print(f'||{f"{n} - 4 = {n - 4}":^15}||')
print(f'||{f"{n} - 5 = {n - 5}":^15}||')
print(f'||{f"{n} - 6 = {n - 6}":^15}||')
print(f'||{f"{n} - 7 = {n - 7}":^15}||')
print(f'||{f"{n} - 8 = {n - 8}":^15}||')
print(f'||{f"{n} - 9 = {n - 9}":^15}||')
